starter_key: "scroll-up"
combo_name : "Precision Bolt"
all_guns:
  - "1" #CombatShotgun
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8" #BFG9000
cycle_guns:
  #- "2"
  #- "1"
  - "2"
  - "6"
  #- "Grenade" #Grenade will be auto shoot
  - "2"
  - "4"
  - "2"
  - "5"
next_weapon_when:
  "2" : "left_release"
  "4" : "left_release"
  "5" : "left_release"
  "6" : "left_release"
switch_when:
  "2" : "right left"
  "5" : "left"
  "6" : "left"