starter_key: "middle-release"
name : "Rocker Launcher"
spam_delay : 0.5
macro_type : "combo"
all_guns:
  - "1" #CombatShotgun
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8" #BFG9000
cycle_guns:
  - "4"
  - "2"
next_weapon_when:
  "2" : "left_release"
  "4" : "left_release"
  "5" : "left_release"
  "6" : "left_release"
switch_when:
  "2" : "right left"
  "4" : "left"
  "5" : "left"
  "6" : "left"