starter_key: "scroll-down"
name : "Super Shotgun"
spam_delay : 0.5
macro_type: "combo"

cycle_guns:
  #- "5"
  #- "2"
  - "5"
  - "4"
  - "6"

next_weapon_when:
  "2" : "left_release"
  "5" : "left_release"
  "6" : "left_release"
  "4" : "left_release" #Detonator
switch_when:
  "2" : "right left"
  "5" : "left"
  "6" : "left"