start_when:
  mouse : "scroll_up"
name : "Ballista"
spam_delay : 0.5
macro_type: "combo"
cycle_guns:
  - "Precision Bolt"
  - "Ballista"
next_weapon_when:
  "Precision Bolt"  : "left_release"
  "Ballista"        : "left_release"