start_when:
  current_weapon : "Microwave Beam"
name : "Microwave Beam"
macro_type: "combo"
cycle_guns:
  - "Microwave Beam"
  - "Rocket Launcher"
next_weapon_when:
  "MicroWave Beam" : "left_release"
  "Rocket Launcher" : "left_release"