#mods_key = access
"Combat Shotgun":
  access : "user_keyboard_1_down"
  mods : ["Sticky Bomb","Full Auto"]
  cursor_imgs : ["cursor/Sticky Bomb.tif","cursor/Full Auto.tif"]
"Heavy Cannon":
  access : "user_keyboard_2_down"
  mods : ["Precision Bolt","Micro Missiles"]
"Plasma Rifle":
  access : "user_keyboard_3_down"
  mods : ["Heat Blast","Microwave Beam"]
"Rocket Launcher":
  access : "user_keyboard_4_down"
  mods : ["Detonator","Lock-On Burst"]
"Super Shotgun":
  access : "user_keyboard_5_down"
  mods : null
"Ballista":
  access : "user_keyboard_6_down"
  mods : ["Arbalest","Destroyer Blade"]
"Chaingun":
  access : "user_keyboard_7_down"
  mods : ["Mobile Turret","Energy Shield"]
#BFG is the odd one here


"Crucible":
  access : "user_keyboard_v_down"

